server_active: centos-active
server_passive: centos-passive
server_active_host: 10.100.199.20
server_passive_host: 10.100.199.30

vms: [
      { name: centos-storage, ip: 10.100.199.10 },
      { name: "{{ server_active }}", ip: "{{ server_active_host }}" },
      { name: "{{ server_passive }}", ip: "{{ server_passive_host }}" }
     ]
     

oracle_jdk_version: 8
oracle_jdk_update: 111
oracle_jdk_build_number: b14

# RedHat family specific variables
oracle_jdk_rpm_download_filename: jdk-{{ oracle_jdk_version }}u{{ oracle_jdk_update }}-linux-x64.rpm
oracle_jdk_rpm_download_source_url: http://download.oracle.com/otn-pub/java/jdk/{{ oracle_jdk_version }}u{{ oracle_jdk_update }}-{{ oracle_jdk_build_number }}/{{ oracle_jdk_rpm_download_filename }}

eap_version: jboss-eap-7.0.0
eap_filename: "{{ eap_version }}.zip"