---

- name: Install common utils.
  yum: state=present name="{{ item }}"
  with_items:
    - git
  register: result
  
  #TODO
#- name: Install the UCP controller
#  docker_container:
#    name: jenkins
#    image: jenkins
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "/etc/docker_subscription.lic:/docker_subscription.lic"
#    command: install --host-address {{ ansible_host }} --admin-password {{ ucp_admin_password }} --san {{ ansible_hostname }}
#    state: started
#    detach: true
#    cleanup: yes