---
# This is the main playbook what ansible will use for provisoning. 
- hosts: ha-systems
  become: yes
  become_method: sudo
  serial: "100%"
  roles:
    - add-hosts
    - utils-tools
    - jdk-8
    - cluster-software-pack
    - httpd-server-cluster
    - drdb
#    - jenkins # TODO Standard Install 
#    - jenkins-cluster # TODO Config clustering 
#    - jenkins-replication  # TODO Possibly gluster
    
    
