---
# This is the main playbook what ansible will use for provisoning. 
- hosts: gateway-systems
  become: yes
  become_method: sudo
  serial: 1
  roles:
    - add-hosts
    - utils-tools
    - gateway-software-pack