---
# This is the main playbook what ansible will use for provisoning. 
- hosts: storage-systems
  become: yes
  become_method: sudo
  serial: 1
  roles:
    - add-hosts
    - utils-tools
#    - storage-software-pack