---


- name: install drdb84
  yum:
    name: http://elrepo.org/linux/elrepo/el7/x86_64/RPMS/drbd84-utils-8.9.6-1.el7.elrepo.x86_64.rpm
    state: present

- name: install kmod-drdb84
  yum:
    name: http://elrepo.org/linux/elrepo/el7/x86_64/RPMS/kmod-drbd84-8.4.8-1_1.el7.elrepo.x86_64.rpm
    state: present