---

- stat: path=/tmp/{{ oracle_jdk_rpm_download_filename }}
  register: jdk_rpm
  
- name: download oracle-jdk rpm
  when: jdk_rpm.stat.exists == False
  get_url:
    url: "{{ oracle_jdk_rpm_download_source_url }}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest: /tmp/{{ oracle_jdk_rpm_download_filename }}

- name: install oracle-jdk
  yum:
    name: /tmp/{{ oracle_jdk_rpm_download_filename }}
    state: present

- name: configure installed java
  alternatives:
    name: java
    path: /usr/java/jdk1.{{ oracle_jdk_version }}.0_{{ oracle_jdk_update }}/bin/java
    link: /usr/bin/java