---

- stat: path=/tmp/{{ oracle_jdk_rpm_download_filename }}
  register: jdk_rpm
    
- name: copy oracle-jdk rpm
  when: jdk_rpm.stat.exists == False
  copy:
    src: /tmp/{{ oracle_jdk_rpm_download_filename }}
    dest: /tmp/{{ oracle_jdk_rpm_download_filename }}

- name: install oracle-jdk
  yum:
    name: /tmp/{{ oracle_jdk_rpm_download_filename }}
    state: present

- name: configure installed java
  alternatives:
    name: java
    path: /usr/java/jdk1.{{ oracle_jdk_version }}.0_{{ oracle_jdk_update }}/bin/java
    link: /usr/bin/java
    
 